name: Chuyên
url: "https://xn--chuyn-ksa.vn"
title: "Random thoughts"
markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']
paginate: 4
rtl: false
owner:
  twitter: vdchuyen
  linkedin: https://www.linkedin.com/in/chuyenvd
