site.title: "Tổ chim"
url: "https://xn--chuyn-ksa.vn"
markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']
paginate: 4
description: "Rác tha lâu đầy tổ"
rtl: false
owner:
  twitter: chuyen__
  linkedin: https://www.linkedin.com/in/chuyenvd
  lastfm: chuyen_
  github: https://github.com/vdchuyen
